environment_version: 1
credentials:
- type: aws
  id: HhrEpXBoPE83ua37
  description: AWS Assumable Role - aind-codeocean-user
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: gelxYrUQTUSB54Y7
  description: data_asset_manipulations
  key: API_KEY
  secret: API_SECRET

